version: '3'

services:
  mysql:
    image: "mysql:5.5"
    restart: "always"
    container_name: "mysql"
    volumes:
      - ${ROOTFS_DATA}:/data     
    ports:
      - "3306:3306"
    environment:
      - MYSQL_USER=${SYSNAME}
      - MYSQL_PASSWORD=${MYSQL_ROOT_PASSWORD}
      - MYSQL_ROOT_PASSWORD=${MYSQL_ROOT_PASSWORD}
      - MYSQL_DATABASE=${SYSNAME}

  web:
    image: "node"
    restart: "always"
    container_name: "${SYSNAME}"
    command: "npm start"
    working_dir: /web
    volumes:
      - ${ROOTFS_DATA}/:/data      
      - .:/web
    links:
      - mysql
    ports:
      - "443:443" 
